In [4]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import solve_triangular

%matplotlib inline

In [5]:
plt.style.use("dark_background")

In [58]:
xx = np.loadtxt("./xx", delimiter=",")
xy = np.loadtxt("./xy", delimiter=",")

In [59]:
xx_inv = np.linalg.inv(xx)

In [69]:
actual = np.linalg.inv(xx).dot(xy)

In [61]:
def subset_regression(xx_in, xy_in, indices):
    xx_filtered = np.take(np.take(xx_in, indices, axis=1), indices, axis=0)
    xy_filtered = np.take(xy_in, indices)
    R = np.linalg.cholesky(xx_filtered)
    w = solve_triangular(a=R, b=xy_filtered, lower=True)
    betas = solve_triangular(R.T, w)
    sse = - betas.T.dot(xy_filtered)
    return betas, sse

In [62]:
subset_regression(xx, xy, [2, 5, 7])

(array([ 793.37025259, -298.62467051,  565.61878285]), -1063275.9922720208)

In [63]:
num_features = len(xy)

In [64]:
max_features = 10

In [66]:
all_indices = range(num_features)
remaining_idx = all_indices
selected_idxs = []
overall_sse = []
curr_betas = None
while len(remaining_idx) > 0 and len(selected_idxs) <= max_features:
    print("len(ri): ", len(remaining_idx))
    betas = []
    sse = []
    for feature in remaining_idx:
        check_idx = np.append(selected_idxs, [feature]).tolist()
        print(check_idx)
        b, s = subset_regression(xx, xy, check_idx)
        betas.append(b)
        sse.append(s)

    idx = remaining_idx[np.argmin(sse)]
    min_sse = np.min(sse)
    overall_sse.append(min_sse)
    print(curr_betas)
    print(idx)
    selected_idxs.append(idx)
    print("Selected: ", selected_idxs)
    remaining_idx = np.setdiff1d(all_indices, selected_idxs)
    print("Remaining: ", remaining_idx)
    print("Overall SSE: ", overall_sse)
    curr_betas = np.array(betas).copy()

('len(ri): ', 10)
[0.0]
[1.0]
[2.0]
[3.0]
[4.0]
[5.0]
[6.0]
[7.0]
[8.0]
[9.0]
None
2
('Selected: ', [2])
('Remaining: ', array([0, 1, 3, 4, 5, 6, 7, 8, 9]))
('Overall SSE: ', [-901427.313660403])
('len(ri): ', 9)
[2, 0]
[2, 1]
[2, 3]
[2, 4]
[2, 5]
[2, 6]
[2, 7]
[2, 8]
[2, 9]
[[ 304.18307453]
 [  69.71535568]
 [ 949.43526038]
 [ 714.7416437 ]
 [ 343.25445189]
 [ 281.78459335]
 [-639.14527932]
 [ 696.88303009]
 [ 916.13872282]
 [ 619.22282068]]
8
('Selected: ', [2, 8])
('Remaining: ', array([0, 1, 3, 4, 5, 6, 7, 9]))
('Overall SSE: ', [-901427.313660403, -1204315.0171108374])
('len(ri): ', 8)
[2, 8, 0]
[2, 8, 1]
[2, 8, 3]
[2, 8, 4]
[2, 8, 5]
[2, 8, 6]
[2, 8, 7]
[2, 8, 9]
[[ 924.81645876  133.01372901]
 [ 950.67813854  -14.09775904]
 [ 790.39655461  402.20673622]
 [ 921.1686165   113.16732987]
 [ 939.95572214   36.2964409 ]
 [ 826.14824417 -336.10503357]
 [ 797.64611521  366.81180169]
 [ 675.06977443  614.95050478]
 [ 834.8833507   294.72036503]]
3
('Selected: ', [2, 8, 3])
('Remaining: '

In [67]:
curr_betas

array([[ 519.83978679,  751.27932109,  324.39042769, -792.18416163,
        -239.81908937,  476.74583782,  177.06417623,   67.62538639,
         101.04457032,  -10.01219782]])

In [70]:
actual[selected_idxs]

array([ 519.83978679,  751.27932109,  324.39042769, -792.18416163,
       -239.81908937,  476.74583782,  177.06417623,   67.62538639,
        101.04457032,  -10.01219782])